name: Inspect Visual C++ Redistributables

on:
  push:
  workflow_dispatch:

jobs:
  check-vc-runtime:
    runs-on: windows-l2022

    steps:
    - name: Check Installed Visual C++ Runtimes
      shell: pwsh
      run: |
        Write-Host "Checking installed Visual C++ Redistributables..."
        Get-ChildItem -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall" |
        ForEach-Object {
            $DisplayName = $_.GetValue("DisplayName", $null)
            $Version = $_.GetValue("DisplayVersion", $null)
            if ($DisplayName -like "*Microsoft Visual C++*") {
                Write-Output "$DisplayName - Version: $Version"
            }
        } | Out-File -FilePath vc_runtimes.txt -Encoding utf8
        Write-Host "Visual C++ runtime details saved to vc_runtimes.txt"

    - name: Display Visual C++ Runtimes
      shell: pwsh
      run: |
        if (Test-Path vc_runtimes.txt) {
            Write-Host "Displaying installed Visual C++ runtimes:"
            Get-Content vc_runtimes.txt
        } else {
            Write-Host "Error: vc_runtimes.txt not found."
        }
